erofs/zdata: Include missing kthread header
This fixes the following compilation errors:

../fs/erofs/zdata.c:135:4: error: implicit declaration of function 'kthread_destroy_worker' [-Werror,-Wimplicit-function-declaration]
                        kthread_destroy_worker(worker);
                        ^
../fs/erofs/zdata.c:144:3: error: implicit declaration of function 'kthread_create_worker_on_cpu' [-Werror,-Wimplicit-function-declaration]
                kthread_create_worker_on_cpu(cpu, 0, "erofs_worker/%u", cpu);
                ^
../fs/erofs/zdata.c:194:3: error: implicit declaration of function 'kthread_destroy_worker' [-Werror,-Wimplicit-function-declaration]
                kthread_destroy_worker(worker);
                ^
../fs/erofs/zdata.c:210:3: error: implicit declaration of function 'kthread_destroy_worker' [-Werror,-Wimplicit-function-declaration]
                kthread_destroy_worker(worker);
                ^
../fs/erofs/zdata.c:934:4: error: implicit declaration of function 'kthread_queue_work' [-Werror,-Wimplicit-function-declaration]
                        kthread_queue_work(worker, &io->u.kthread_work);
                        ^
../fs/erofs/zdata.c:1337:3: error: implicit declaration of function 'kthread_init_work' [-Werror,-Wimplicit-function-declaration]
                kthread_init_work(&q->u.kthread_work,
                ^

Place kthread.h at zdata.h, otherwise compiler will break compilation since kthread_work
has an incomplete type struct.

Fixes: e5fe45ddb87 ("BACKPORT: erofs: add per-cpu threads for decompression as an option")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>